### ISSUE TITLE
Support Multi-lingual: Add in the UI a selector for which language to show for the ontologies data

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#165]
### Context
Currently, in the UI, we don't have any to show other data languages than English.

The idea is to give the user the possibility to show one on multiple languages in the UI for ontologies data, like concept prefLabel, synonyms, and definitions,... 

### References
see what's done in SKOSMOS and ShowVoc

- https://stats.fao.org/caliper/browse/showvoc/#/datasets/Forest_Products_2016/data?resId=https:%2F%2Fstats.fao.org%2Fclassifications%2FFPCD%2Fv2016%2F07
- https://skosmos.loterre.fr/3JP/fr/page/-XL1XVZF4-6
- https://thesaurus.inrae.fr/thesaurus-inrae/fr/page/?uri=c_25372&clang=fr&anylang=on

### Implementation

- https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/216
- https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/225
- https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/239
- https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/231

**Comment by jonquet** [comment]
After discussion today : 
- Selector to position ion the UI at the level of the ontology 'on the right) 
 <img width="1401" alt="image" src="https://user-images.githubusercontent.com/7379183/223681271-53b218ba-217e-47e2-9c5c-84cc2b163bf2.png">
This selector must be populated with the naturalLanguage metadata property and explicitly say if the property is empty (so that the admin can fill in). 

- We keep the no_lang values even when a language is selected
- We never retrieve (no more fallback) other languages if the one specified is not found
- UI should manage the nil and [] possibilities in the previous case.

**Comment by syphax-bouazzouni** [comment]
Deployed in production in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/240
