### ISSUE TITLE
Phrase mentionnant une date non localisée

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#604]
<img width="334" alt="Capture d’écran 2024-04-27 à 12 23 23" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/25206e51-aecc-470a-b070-8b4d2b0d75ec">

La version francaise de la prhase devrait etre: 
"Date de la dernière soumission le 25 avril 2024"
ou meme encore plus simple 
"Dernière soumission : 25 avril 2024"
et en anglais
"Last submission: April 25, 2024"

(bien faire attention aux espaces ou pas avant les 2 points => en francais oui, en anglais non)

**Comment by syphax-bouazzouni** [comment]
fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/613

### French version 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/bff76130-a2c7-4bd6-843b-9c4430297a48)


### English version

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/5a59d201-bd41-4c0c-bcd4-4a086bf5d123)
