### ISSUE TITLE
Migrate label_ajax_controller.js code to turbo rails

### ISSUE THREAD

**Issue by Bilelkihal** [ontoportal-lirmm/bioportal_web_ui#647]
### Description:
Currently the code related to determine whether the chips buttons in our concept details page is internal or external (internal: like a concept or an ontology in agroportal, so we need to open it in AgroPortal. External: like any external link that take out of the portal) is written in JS, we need to re write it using turbo rails.

**Comment by syphax-bouazzouni** [comment]
Related to https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/638

There are two issues with our current approach:
- We don't control the order of the AJAX calls: When you go to a page, for example ontology concepts, it will show the page, then, behind the scenes a lot of Ajax calls, to get the tree, the details of the concept, and mappings, .... But the issue is in the order/priority of the requests, we don't control it, and we can have like the bellow case; where I'm on the concept page, but we fetch before all the other pages, then get the concepts labels last.
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/13138073-71dc-4d81-afcf-1a2c233ed9cd)


- We do the call for each label in the UI,  even if we never go to that page. For example when you are only on the summary page, at the same time requests are done in the mapping, schemes, concepts, ... pages (hidden), to fetch the concepts labels. Making a lot of unnecessary requests => Using Turbo frame in lazy mode, will solve this, by doing the calls only when the labels are visible in the UI (visited by the user).

**Comment by syphax-bouazzouni** [comment]
Related https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/129

**Comment by syphax-bouazzouni** [comment]
Moved to https://github.com/agroportal/project-management/issues/583
