### ISSUE TITLE
Adding new groups to an ontology via UI does not work

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#66]
For some reason, when I try to add a group to SO, TO, PO and some others, via the UI it does not work. 

<img width="838" alt="image" src="https://user-images.githubusercontent.com/7379183/159467161-21302be3-bcf4-4758-94e3-cad9eed5066a.png">

Maybe the selection in the UI of the groups does not erase the value already entered .

**Comment by syphax-bouazzouni** [comment]
Two problems there : 

1. A UI problem where the group's field is not well displayed, it should be shown like below (fixed by https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/67)
![image](https://user-images.githubusercontent.com/29259906/159649230-187d4720-f321-47e8-ba00-4757cbea8627.png)

2. An update process problem, where the change is not taken (fixed here
