### ISSUE TITLE
Qu'est ce que cette propriété prefixIRI fait la ?

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#743]
https://data.stageportal.lirmm.fr/ontologies/OBOE/properties/http%3A%2F%2Fdata.bioontology.org%2Fmetadata%2FprefixIRI

Elle se retrouve visiblement apres le parsing OWL-API dans les ontologies.
OBOE RDF/XML produced file: 
<img width="902" alt="Capture d’écran 2024-09-04 à 16 57 40" src="https://github.com/user-attachments/assets/28be8525-463b-43cd-94ad-814c0362a3c6">

**Comment by syphax-bouazzouni** [comment]
This property is added by us in the parsing step, originally implemented by ncbo in 2013, https://github.com/ncbo/owlapi_wrapper/commit/f7cf5c973aed61b01ff4d3ab365ea0051905df39
This value is saved and can be used to fetch a class using the prefixed IRI instead of the full URI. 

Example calling https://data.stageportal.lirmm.fr/ontologies/OBOE/classes/oboe-characteristics:Angle 
Instead of  https://data.stageportal.lirmm.fr/ontologies/OBOE/classes/http%3A%2F%2Fecoinformatics.org%2Foboe%2Foboe.1.2%2Foboe-characteristics.owl%23Angle
