### ISSUE TITLE
Refactor Summary page

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#75]
Description to come. See notes in : 
https://docs.google.com/document/d/1gJbGcHCP5fhhFJ-VCo08wvOJGpTOtb3XPoOsmvT-Q-Q/edit#heading=h.kxi8ast0cchr

**Comment by syphax-bouazzouni** [comment]
Related https://github.com/agroportal/project-management/issues/236

**Comment by hibadjebabria169** [comment]
- Be inspired by the structuring of the input page for the groupings : be careful that some sections will sometimes be almost empty because some fields are not filled in.
- Graphical representation of relationships between ontologies, like the Landscape page with the name of the relationship on the arc and the nodes clickable and turned into buttons when they correspond to AgroPortal ontologies.
- Transform the groups and categories into links that open a "pop up" to describe the groups and categories and list the other ontologies that are in that group or category. Beware there is no page in OntoPortal that displays the groups/categories. 
- **Acronym** :  Delete the row from the table and add the acronym in parenthesis after the ontology name in the title
- **Visibility** :  Transform it by an open or closed cadena icon  
- **Description** :  remove the name of the metadata, put it in justified and italic.
- **Format** : To be transformed by a small icon that gives the format 
- **Contact** : To be transformed by a @ icon 
- **Endpoin**t : Delete the line and always display the clickable icon with the value 
- **Natural language** : Put the flags elsewhere but not in a bar at the top to avoid confusion with the icons of change of language of the interface
- **HasLicense** :  same elsewhere and keep only the icon
- **Alternative name** : put under the main name in small prefixed with "A.k.a: ".
- **Has prior version** : remove from the table and in case it is an external URI (and not a link to the previous submission in AgroProtal) then put it in a row under the current submission in the submission table. 
- **Release Date** : remove it from the table because it is already in the submission table
- **Button "Go to the rest API"** : to change by an icon (already present elsewhere on the portal) 
Get my metadataback : keep the idea of a single button (which allows to choose the profile) and put it at the bottom of the page

**Comment by jonquet** [comment]
@Bilelkihal to create the Correpsonding Figma page on 
https://www.figma.com/file/n2tOIfgVlVvFAr3F00Ab5m/Ontoportal-alliance?node-id=158%3A6&t=Rhy7sX9rog6GQnLd-0
