### ISSUE TITLE
Create UNESCO categories

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#752]

**Comment by jonquet** [comment]
This issue is about creating Categories in AgroPortal following the UNESCO nomenclature for fields of science and technology. 

Old categories have been saved in: https://github.com/agroportal/project-management/blob/master/groups-categories/categories.json

New categories are now saved in this file, but coming from an old version of UNESCO
https://skos.um.es/unesco6/view.php?l=en&fmt=1

Need to be done again with @saubin with the recent UNECO thesaurus at 
https://vocabularies.unesco.org/browser/thesaurus

**Comment by saubin78** [comment]
@jonquet I indicated related concepts from UNESO thésaurus as much as I could. Note that they are more keywords than categories or thematics. I could have used the UNESCO thesaurus "groups" instead of concepts but their granularity was too large to fit Agroportal's

**Comment by jonquet** [comment]
Where did you do this?

**Comment by saubin78** [comment]
https://docs.google.com/spreadsheets/d/163_6fJs_SDIQR09I4RUK70DgtTPtt4WpXIOXzb1I0Ug/edit?gid=1305831292#gid=1305831292 Tab « new categories”, column E

De : Clement Jonquet ***@***.***>
Envoyé : vendredi 20 septembre 2024 07:04
À : ontoportal-lirmm/bioportal_web_ui ***@***.***>
Cc : Sophie Aubin ***@***.***>; Mention ***@***.***>
Objet : Re: [ontoportal-lirmm/bioportal_web_ui] Create UNESCO categories (Issue #752)


Where did you do this?

**Comment by jonquet** [comment]
@user34ngrau Can you finish the file: https://github.com/agroportal/project-management/blob/master/groups-categories/categories.json and make pull request on GitHub?

**Comment by saubin78** [comment]
We should discuss this more extensively before changing the categories. I'm not sure at all that UNESCO thesaurus is relevant for what you want to do (I probably misunderstood your intention). A classification vocabulary would be better than this one.

**Comment by syphax-bouazzouni** [comment]
Done in AgroPortal and categories assigned
