### ISSUE TITLE
AgroPortal recommender API not working

### ISSUE THREAD

**Issue by Bilelkihal** [ontoportal-lirmm/bioportal_web_ui#825]
![image](https://github.com/user-attachments/assets/67c5c1cf-b1a6-4c63-aee1-d055064f3b81)

**Comment by syphax-bouazzouni** [comment]
The issue is in this line https://github.com/ontoportal-lirmm/ontologies_api/blob/master/Gemfile#L51, we should use our version of the recommender, not the NCBO. Probably an issue when merging. 

Fixed  and deployed in Agroportal and Stageportal  
![image](https://github.com/user-attachments/assets/10902d47-fefc-4652-b248-89933e914586)
